---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: _data/configuration.yml
  label: Configuration
- type: directory
  path: _pages
  label: Contenu
  create: documents
  match: "**/*"
  templates:
  - contenu
- type: directory
  path: _projects
  label: Projets
  create: all
  match: "**/*"
  templates:
  - projet
- type: directory
  path: _articles
  label: Articles
  create: all
  match: "**/*"
upload_dir: _assets/img
public_path: "/_assets/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
