---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _data
  label: Page d'accueil
  create: documents
  match: "*"
  new_doc_ext: ".yml"
- type: directory
  path: _pages
  label: Pages de contenu
  create: documents
  match: "**/*"
- type: directory
  path: _projects
  label: Projets
  create: all
  match: "**/*"
- type: directory
  path: _articles
  label: Articles
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
