---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: _data/configuration.yml
  label: Configuration
- type: directory
  path: _pages
  label: Contenu
  create: documents
  match: "**/*"
  templates:
  - contenu
- type: directory
  path: _projects
  label: Projets
  create: all
  match: "**/*"
  templates:
  - projet
- type: directory
  path: _articles
  label: Articles
  create: all
  match: "**/*"
  templates:
  - article
upload_dir: _assets/img
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_env:
  - JEKYLL_ENV=staging
  - RUBY_VERSION=2.6.1
  preview_output_directory: _site
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
